# Configuration file for controls in the model

# Specify the size of the microenvironment
room-length:
  id: ctrl-room-length
  description: |
      The length of the room in meters.
  type: number
  options:
    minimum: 1
    maximum: None
  default: 30.0

room-width:
  id: ctrl-room-width
  description: |
      The width of the room in meters.
  type: number
  options:
    minimum: 1
    maximum: None
  default: 20.0

room-height:
  id: ctrl-room-height
  description: |
      The height of the room in meters.

      *A residential room will typically have a ceiling height of 2.7-3.0 meters.*
  type: number
  options:
    minimum: 1
    maximum: None
  default: 3.0

# Ventilation rates for the building
ventilation-aer:
  id: ctrl-ventilation-aer
  description: |
      The Air Exchange Rate per hour (AER) of the environment.

      *A residential rooom will have an AER in the range 0.2-1.0*
  type: number
  options:
    minimum: 0.1
    maximum: None
  default: 1.1

 # Controls for exhalation rate
exhalation-rate:
  id: ctrl-exhalation-rate
  description: |
      Level of activity for people in the environment.
  type: dropdown
  options:
    option1:
      label: Resting
      value: 98.1
    option2:
      label: Standing
      value: 147
    option3:
      label: Light exercise
      value: 317
  default: option2
  
exhalation-mask:
  id: ctrl-exhalation-mask
  description: |
    Face coverings worn by the majority of people in the environment.
  type: dropdown
  options:
    option1:
      label: No mask
      value: 0.0
    option2:
      label: Cloth mask
      value: 0.2
    option3:
      label: Surgical mask
      value: 0.5
    option4:
      label: Respirator
      value: 0.95
  default: option1
  
# Occpancy determines the average distance between people
average-occupancy:
    id: ctrl-average-occupancy
    description: |
      The average occupancy of the environment. 

      *The more people in a room the harder it will be to maintain physical distancing.*
    type: number
    options:
      minimum: 1
      maximum: None
    default: 60

# Controls for inhalation rate
inhalation-rate:
  id: ctrl-inhalation-rate
  description: |
    Level of activity for people in the environment.
  type: dropdown
  options:
    option1:
      label: Resting
      value: 0.36
    option2:
      label: Standing
      value: 0.54
    option3:
      label: Light exercise
      value: 1.16
  default: option2
  
inhalation-mask:
  id: ctrl-inhalation-mask
  description: |
    Wearing a face covering does reduce the risk of infection unless it is specfically designed to do so.
  type: dropdown
  options:
    option1:
      label: No mask
      value: 0.0
    option2:
      label: Cloth mask
      value: 0.2
    option3:
      label: Surgical mask
      value: 0.5
    option4:
      label: Respirator
      value: 0.95
  default: option1

# The time that a person is in the environment.
time-in-environment:
  id: ctrl-time-in-environment
  description: |
    The average amount of time people are in the environment in minutes.
    
    *Time in the environment is a critical risk factor.*
  type: number
  options:
    minimum: 1
    maximum: None
  default: 30
  
  
  
  
  
  
  